spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    com.stu.benchmark: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
