spring:
  datasource:
    hikari:
      # Tomcat ㅅ스레드(200)에 대응하여 커넥션 부족 에러 방지
      maximum-pool-size: 150
      connection-timeout: 5000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: warn
    com.stu.benchmark: info
    org.hibernate.SQL: error  # I/O 부하 최소화
