spring:
  datasource:
    hikari:
      # Tomcat ㅅ스레드(200)에 대응하여 커넥션 부족 에러 방지
      maximum-pool-size: 150
      connection-timeout: 5000
  data:
    redis:
      lettuce:
        pool:
          max-active: 100 # 동시에 사용할 수 있는 최대 커넥션 개수
          max-idle: 50 # 대기 상태로 유지할 최대 커넥션
          min-idle: 10 # 최소 유지 커넥션
          max-wait: 3000ms # 커넥션 획득 대기 타임아웃
          time-between-eviction-runs: 10000ms # 유휴 커넥션 검사 주기
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

redisson:
  lock:
    # TODO: waitTime(3~10초)·leaseTime(2~5초) 또는 워치독(-1)으로 조정하며 성능 평가
    wait-time: 5000 # 락 획득 대기 시간 (ms)
    lease-time: 3000 # 락 유지 시간 (ms)

logging:
  level:
    root: warn
    com.stu.benchmark: info
    org.hibernate.SQL: error # I/O 부하 최소화

management:
  tracing:
    enabled: false
