global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Spring Boot 애플리케이션 모니터링
  - job_name: "concurrency-control"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["was1:8080", "was2:8080"]

  # Redis 매트릭 수집
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
